#!/usr/bin/env python3

import sys

def factorize(number):
    factors = []
    for i in range(2, int(number**0.5) + 1):
        while number % i == 0:
            factors.append(i)
            number //= i
    if number > 1:
        factors.append(number)
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as file:
            for line in file:
                number = int(line.strip())
                factors_list = factorize(number)
                factors_str = '*'.join(map(str, factors_list))
                print("{}={}".format(number, factors_str))

    except FileNotFoundError:
        print("Error: File '{}' not found.".format(input_file))
        sys.exit(1)

if __name__ == "__main__":
    main()
