#!/usr/bin/env python3

import sys
import math

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

def factorize_rsa(number):
    for i in range(2, int(math.sqrt(number)) + 1):
        if number % i == 0 and is_prime(i) and is_prime(number // i):
            return i, number // i
    return None, None

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as file:
            for line in file:
                number = int(line.strip())
                prime1, prime2 = factorize_rsa(number)
                if prime1 is not None and prime2 is not None:
                    print("{}={}*{}".format(number, prime1, prime2))
                else:
                    print("{} is not factorizable into two prime numbers.".format(number))

    except FileNotFoundError:
        print("Error: File '{}' not found.".format(input_file))
        sys.exit(1)

if __name__ == "__main__":
    main()
